package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseContract<M extends BaseContract<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setConname(java.lang.String conname) {
		set("conname", conname);
		return (M)this;
	}
	
	public java.lang.String getConname() {
		return getStr("conname");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public M setPartya(java.lang.String partya) {
		set("partya", partya);
		return (M)this;
	}
	
	public java.lang.String getPartya() {
		return getStr("partya");
	}

	public M setPartyb(java.lang.String partyb) {
		set("partyb", partyb);
		return (M)this;
	}
	
	public java.lang.String getPartyb() {
		return getStr("partyb");
	}

	public M setPartyatel(java.lang.String partyatel) {
		set("partyatel", partyatel);
		return (M)this;
	}
	
	public java.lang.String getPartyatel() {
		return getStr("partyatel");
	}

	public M setPartybtel(java.lang.String partybtel) {
		set("partybtel", partybtel);
		return (M)this;
	}
	
	public java.lang.String getPartybtel() {
		return getStr("partybtel");
	}

	public M setStarttime(java.util.Date starttime) {
		set("starttime", starttime);
		return (M)this;
	}
	
	public java.util.Date getStarttime() {
		return get("starttime");
	}

	public M setPaytime(java.util.Date paytime) {
		set("paytime", paytime);
		return (M)this;
	}
	
	public java.util.Date getPaytime() {
		return get("paytime");
	}

	public M setPay(java.lang.String pay) {
		set("pay", pay);
		return (M)this;
	}
	
	public java.lang.String getPay() {
		return getStr("pay");
	}

	public M setPaytime1(java.util.Date paytime1) {
		set("paytime1", paytime1);
		return (M)this;
	}
	
	public java.util.Date getPaytime1() {
		return get("paytime1");
	}

	public M setPay1(java.lang.String pay1) {
		set("pay1", pay1);
		return (M)this;
	}
	
	public java.lang.String getPay1() {
		return getStr("pay1");
	}

	public M setPaytime2(java.util.Date paytime2) {
		set("paytime2", paytime2);
		return (M)this;
	}
	
	public java.util.Date getPaytime2() {
		return get("paytime2");
	}

	public M setPay2(java.lang.String pay2) {
		set("pay2", pay2);
		return (M)this;
	}
	
	public java.lang.String getPay2() {
		return getStr("pay2");
	}

	public M setPaytime3(java.util.Date paytime3) {
		set("paytime3", paytime3);
		return (M)this;
	}
	
	public java.util.Date getPaytime3() {
		return get("paytime3");
	}

	public M setPay3(java.lang.String pay3) {
		set("pay3", pay3);
		return (M)this;
	}
	
	public java.lang.String getPay3() {
		return getStr("pay3");
	}

	public M setIstrue(java.lang.String istrue) {
		set("istrue", istrue);
		return (M)this;
	}
	
	public java.lang.String getIstrue() {
		return getStr("istrue");
	}

	public M setBeizhu(java.lang.String beizhu) {
		set("beizhu", beizhu);
		return (M)this;
	}
	
	public java.lang.String getBeizhu() {
		return getStr("beizhu");
	}

	public M setUserid(java.lang.String userid) {
		set("userid", userid);
		return (M)this;
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

	public M setLeadtime(java.util.Date leadtime) {
		set("leadtime", leadtime);
		return (M)this;
	}
	
	public java.util.Date getLeadtime() {
		return get("leadtime");
	}

}
