package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRibao<M extends BaseRibao<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setUserid(java.lang.String userid) {
		set("userid", userid);
		return (M)this;
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

	public M setDepid(java.lang.String depid) {
		set("depid", depid);
		return (M)this;
	}
	
	public java.lang.String getDepid() {
		return getStr("depid");
	}

	public M setFid(java.lang.String fid) {
		set("fid", fid);
		return (M)this;
	}
	
	public java.lang.String getFid() {
		return getStr("fid");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	public M setProblem(java.lang.String problem) {
		set("problem", problem);
		return (M)this;
	}
	
	public java.lang.String getProblem() {
		return getStr("problem");
	}

	public M setBeizhu(java.lang.String beizhu) {
		set("beizhu", beizhu);
		return (M)this;
	}
	
	public java.lang.String getBeizhu() {
		return getStr("beizhu");
	}

}
