package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseContract<M extends BaseContract<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setConname(java.lang.String conname) {
		set("conname", conname);
		return (M)this;
	}
	
	public java.lang.String getConname() {
		return getStr("conname");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public M setPartya(java.lang.String partya) {
		set("partya", partya);
		return (M)this;
	}
	
	public java.lang.String getPartya() {
		return getStr("partya");
	}

	public M setPartyb(java.lang.String partyb) {
		set("partyb", partyb);
		return (M)this;
	}
	
	public java.lang.String getPartyb() {
		return getStr("partyb");
	}

	public M setPartyatel(java.lang.String partyatel) {
		set("partyatel", partyatel);
		return (M)this;
	}
	
	public java.lang.String getPartyatel() {
		return getStr("partyatel");
	}

	public M setPartybtel(java.lang.String partybtel) {
		set("partybtel", partybtel);
		return (M)this;
	}
	
	public java.lang.String getPartybtel() {
		return getStr("partybtel");
	}

	public M setStarttime(java.util.Date starttime) {
		set("starttime", starttime);
		return (M)this;
	}
	
	public java.util.Date getStarttime() {
		return get("starttime");
	}

	public M setPaytime(java.util.Date paytime) {
		set("paytime", paytime);
		return (M)this;
	}
	
	public java.util.Date getPaytime() {
		return get("paytime");
	}

	public M setIstrue(java.lang.String istrue) {
		set("istrue", istrue);
		return (M)this;
	}
	
	public java.lang.String getIstrue() {
		return getStr("istrue");
	}

	public M setBeizhu(java.lang.String beizhu) {
		set("beizhu", beizhu);
		return (M)this;
	}
	
	public java.lang.String getBeizhu() {
		return getStr("beizhu");
	}

	public M setUserid(java.lang.String userid) {
		set("userid", userid);
		return (M)this;
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

}
