package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDep<M extends BaseDep<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setDepname(java.lang.String depname) {
		set("depname", depname);
		return (M)this;
	}
	
	public java.lang.String getDepname() {
		return getStr("depname");
	}

	public M setUserid(java.lang.String userid) {
		set("userid", userid);
		return (M)this;
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

}
