package com.demo.common.model;

import com.demo.common.model.base.BaseContract;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Contract extends BaseContract<Contract> {
	public static final Contract dao = new Contract().dao();
}
