package com.demo.common.model;

import com.demo.common.model.base.BaseDep;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dep extends BaseDep<Dep> {
	public static final Dep dao = new Dep().dao();
}
