package com.demo.common.model;

import com.demo.common.model.base.BaseLiucheng;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Liucheng extends BaseLiucheng<Liucheng> {
	public static final Liucheng dao = new Liucheng().dao();
}
