package com.demo.common.model;

import com.demo.common.model.base.BaseRibao;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ribao extends BaseRibao<Ribao> {
	public static final Ribao dao = new Ribao().dao();
}
