package com.demo.common.model;

import com.demo.common.model.base.BaseShenpi;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Shenpi extends BaseShenpi<Shenpi> {
	public static final Shenpi dao = new Shenpi().dao();
}
