package com.demo.common.model;

import com.demo.common.model.base.BaseZb;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Zb extends BaseZb<Zb> {
	public static final Zb dao = new Zb().dao();
}
